### ISSUE TITLE
Question about the model settings

### ISSUE THREAD

**Issue by ganymedetitan** [facebookresearch/UnsupervisedQA#3]
Hello, thanks for sharing your impressive work and dataset!
I fine-tuned a BERT-base model with the dataset you provided and got 30.70 EM and 38.99 F1 on SQuAD dev set. According to Table 2 in the paper, it is close to the NE-Sentence-Noisy Cloze, which seems not the best of all settings. Is the model trained with this setting? Or did I miss something?
Thanks.

**Comment by patrick-s-h-lewis** [comment]
Hi Ganymedetitian,

Thanks for your interest in our work!

So in the paper, the numbers in table 2 are means over several runs (there can be a bit of variation between each run) but generally the runs would end up with results +/- 1% or 2% of each other, so seeing your delta of ~9% F1 is puzzling. 

One thing that is a bit tricky is knowing when to stop training - the unsupervisedQA dev set data does not correlate that strongly with squad dev set performance, so when the training stops can cause swings in performance (especially early in training) - in the unsupervised case, we cant assume access to a dev set, so our (naive) solution is to train for quite a long time, when downstream performance is more stable. 

The open-sourcing of the code is nearly complete, just need to do some code review. I'll also include a BERT-QA training script in there and verify the open-sourced data can be used to achieve the numbers quoted.

**Comment by patrick-s-h-lewis** [comment]
Dear ganymedetitan,

I have run the training on the opensourced unsupervised QA dataset on bert-base-uncased.
I used HuggingFace's BERTQA implementation (slightly adapted to have lazy dataset loading for memory efficiency reasons, and the training loop counts optimization steps rather than epochs).  

I use a batch size of 16, and all other hyperparameters are kept default, and I used two P100 GPUs. The maximum training time before termination was 40,000 optimisation steps.

I evaluate every 500 steps on the unsupervised QA dev set
Training ended by early stopping at 19,000 optimisation steps, as the score on unsupervised QA dev set does not change by more than 0.1 F1 for the last 3 evaluations.

The results are EM:38.921 F1:48.767 
(a little better than the paper, as I mentioned before, the results in the paper are averaged over several runs, so this is to be expected)
I hope this helps you.
